### ISSUE TITLE
Write function to Autofill student names in the form

### ISSUE THREAD

**Issue by KarthiVi95** [sidharthkmishra/CSE542#101]
Develop a function that queries the database and autofills the students names in the same group dynamically

**Comment by kira2839** [comment]
Test:
1. login with an email id belonging to a student in the first group and check that all your group members and yourself are visible, the first group has 4 students so you should see 4 names.  
2. login with an email id belonging to a student in the first group and check that all your group members and yourself are visible, the first group has 3 students so you should see 3 names.
