### ISSUE TITLE
Submit evaluation.

### ISSUE THREAD

**Issue by kira2839** [sidharthkmishra/CSE542#83]
As a student, I want to fill and submit my evaluations so that I can complete my evaluation process.

**Comment by KarthiVi95** [comment]
User Acceptance Test:

1. Open https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442a/.
2. Enter your UB Email ID.
3. Click on Get Code button.
4. Go to https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442a/index.html#tabs-2. , enter the correct confirmation code entered received in the Email ID.
5. Click on the Start Evaluation button.
6. Read the name of each student in the group and give him/her a rating by selecting an option that best describes his behavior from the drop down menu.
7. Make sure to give ratings for all the students in the group.
8. Click on the Submit Revision button.
9. Go to https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/ and login to the thethys server
10. Click on the cse442_542_2019_summer_teama_db database and click on the student_evaluation table.
11. Click on the browse section and see if corresponding ratings are entered for the corresponding student (This step takes intuitive understanding of how the data are inserted in the tables. Kindly consult with the developers in case of doubt).
