### ISSUE TITLE
Auto-filling student names.

### ISSUE THREAD

**Issue by kira2839** [sidharthkmishra/CSE542#85]
As a professor I want the system to automatically fill in the student names during an evaluation so that there are no spelling mistakes in the names of the students and it will be easier to combine results to generate team score.

**Comment by KarthiVi95** [comment]
User Acceptance Test:

1. Open https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442a/.
2. Enter your UB Email ID.
3. Click on Get Code button.
4. Go to https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442a/index.html#tabs-2. , enter the correct confirmation code entered received in the Email ID.
5. Click on the Start Evaluation button.
6. Read the names of the students the evaluation is asked for.
7. Check if your own name appears in the evaluation form.
8. Make sure that you see all the names of your team mates in the evaluation form.
