### ISSUE TITLE
Ensure each module has a single purpose

### ISSUE THREAD

**Issue by sidharthkmishra** [sidharthkmishra/CSE542#87]
As a code maintainer I want each module in the code to have a single purpose so that it will be easy to maintain and extend the functionality going forward.

**Comment by sidharthkmishra** [comment]
User Acceptance Test:

1. Go to github repos https://github.com/sidharthkmishra/CSE542/tree/develop
2. Check the files names

**Comment by KarthiVi95** [comment]
User Acceptance Test:

1. Go to https://github.com/sidharthkmishra/CSE542.
2. Check if all the functions written in the repository have a single purpose
