### ISSUE TITLE
Develop a function to generate score evaluation form dynamically

### ISSUE THREAD

**Issue by KarthiVi95** [sidharthkmishra/CSE542#88]
A function has to be developed to dynamically create a score evaluation form so that the students can submit their evaluations. The form must change according to the number of students records belonging to the group in the database.

**Comment by kira2839** [comment]
Test:
1. There is dummy data for 2 groups one of 3 members and the other of 4 members so login as a member of each group.
2. For the 3 member group there will be three tables to fill as part of the evaluation and for the 4 member group there will be four tables to fill as part of the evaluation.
