### ISSUE TITLE
The confirmation code should be used only once in start evaluation

### ISSUE THREAD

**Issue by sidharthkmishra** [sidharthkmishra/CSE542#95]
As we can't go for encryption or hashing at javascript as that will not give any security. The only option left is invalidate the code when the student start the evaluation process and we create the session.

**Comment by kira2839** [comment]
Test:
1. Input your confirmation code and login.
2. Immediately close the window and try to login using the same confirmation code, you will be unable to login even if it is within fifteen minutes
