### ISSUE TITLE
Writing input data to the Database tables

### ISSUE THREAD

**Issue by KarthiVi95** [sidharthkmishra/CSE542#97]
Develop functions to store the user input to the student_evaluation table in the database.

**Comment by kira2839** [comment]
Test:
1. Select the first option for all all 5 categories for all members of the group after logging in and submit it.
2. Go to the student_evaluation table at https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/db_structure.php?server=2&db=cse442_542_2019_summer_teama_db&token=975498537c23f4826e702d469f34cec8

3. Check the column fk_student_id and find rows with same value as your login id and you will see that all the numeric values for the cloumns - role, lead, participation, professionalism and quality have all zeroes. 
NOTE: You can find your fk_student_id in the student table in the id column using your email address after logging in.
